# Generated by Django 2.2.12 on 2020-05-12 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_auto_20200512_0301'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Accepted'), (0, 'Declined'), (69, 'Pending')], default=69)),
                ('Approver', models.EmailField(max_length=254)),
                ('JobtaskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Products')),
                ('Requester', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
