# Generated by Django 2.2.12 on 2020-05-11 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(null=True, upload_to='pics')),
                ('desc', models.TextField()),
                ('postedon', models.DateField(auto_now=True)),
                ('expiry', models.DateField()),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Clothes', 'Clothes'), ('Others', 'Others')], max_length=10)),
                ('Status', models.PositiveSmallIntegerField(choices=[(1, 'Completed'), (0, 'Inprogress')], default=0)),
                ('Editor1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Author')),
            ],
        ),
    ]
