# Generated by Django 2.2.12 on 2020-05-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Completed'), (0, 'Inprogress'), (69, 'Cancelled')], default=0),
        ),
    ]
